Output demo/mobile-keyboard-translator.gif

Require mobile-keyboard-translator

Set Shell "bash"
Set Framerate 60
Set FontSize 12
Set Width 800
Set Height 400
Set Padding 20
Set Margin 5
Set MarginFill "#212830"
Set BorderRadius 10

Hide
Type 'cd /tmp/mobile-keyboard-translator-demo && clear' Enter
Show

Type "mobile-keyboard-translator --help" Sleep 200ms Enter
Wait Sleep 1500ms

Enter Enter Type "# translate letters on a phone keypad to digits" Sleep 200ms Enter Enter
Wait Sleep 1000ms

Type "mobile-keyboard-translator 1-800-FLOWERS" Sleep 500ms Enter
Wait Sleep 1500ms

Type "mobile-keyboard-translator 1-800-COLLECT" Sleep 500ms Enter
Wait Sleep 1500ms

Sleep 3s
